### PR TITLE
Ascee's PR

### PR DESCRIPTION
**Pull request by krtab**
Originally sent by email

### CODE REVIEW

**Comment by asceenl** [comment]
Dear krtab,

Can you provide some details on why it is not building on your computer? What OS do you use?

Best regards,

Anne

**Comment by krtab** [comment]
Sure, I get

```shell
error[E0432]: unresolved import `sundials_sys::_SUNContext`
   --> src/lib.rs:108:51
    |
108 | use sundials_sys::{realtype, SUNComm, SUNContext, _SUNContext};
    |                                                   ^^^^^^^^^^^
    |                                                   |
    |                                                   no `_SUNContext` in the root
    |                                                   help: a similar name exists in the module: `SUNContext`

error[E0432]: unresolved import `sundials_sys::_SUNContext`
 --> src/nvector.rs:7:42
  |
7 | use sundials_sys::{realtype, SUNContext, _SUNContext};
  |                                          ^^^^^^^^^^^
  |                                          |
  |                                          no `_SUNContext` in the root
  |                                          help: a similar name exists in the module: `SUNContext`
  |
  = help: consider importing this unresolved item through its public re-export instead:
          crate::_SUNContext

error[E0308]: mismatched types
   --> src/lib.rs:234:44
    |
234 |         let ompi_communicator_t: SUNComm = std::ptr::null_mut();
    |                                  -------   ^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `*mut _`
    |                                  |
    |                                  expected due to this
    |
    = note:     expected type `i32`
            found raw pointer `*mut _`

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `cvode-wrap` (lib) due to 3 previous errors
```

**Comment by asceenl** [comment]
Ah you picked some work in progress. I will finish it soon and update. Will let you know when its working.

**Comment by krtab** [comment]
Perfect, feel free to open PRs here.

**Pull request closed without merging**
